version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - 5678:5432
    environment:
      POSTGRES_DB: express-prisma
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5678
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports: 
      - 6789:6789
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
  postgres-data: